version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-nested-testing-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o9sqx7me36yi"
s3_prefix = "sam-nested-testing-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
